# Python: 
## BASIC FEATURES
https://www.python.org/

In [1]:
print("Hello, World!")

Hello, World!


In [2]:
a = 5
b = 2

In [3]:
a + b

7

In [4]:
1 + a * b

11

In [5]:
a ** b

25

In [6]:
# different in python 3: a//b
# for same behaviour run: from __future__ import division
a / b

2.5

In [7]:
a / float(b)

2.5

In [8]:
a % b

1

In [9]:
min(a, b)

2

In [10]:
a == b

False

In [11]:
a != b

True

In [12]:
a += 3
a

8

In [13]:
#  Python Lists
a = [1, "hello", 5.5]
a

[1, 'hello', 5.5]

In [14]:
len(a)

3

In [15]:
a[2]

5.5

In [16]:
a.append("how are you?")
a

[1, 'hello', 5.5, 'how are you?']

In [17]:
a.insert(2,'Dolly')
a

[1, 'hello', 'Dolly', 5.5, 'how are you?']

In [18]:
for x in a:
    print(x)

1
hello
Dolly
5.5
how are you?


In [19]:
for index, value in enumerate(a):
    print("element {}: {}".format(index, value))

element 0: 1
element 1: hello
element 2: Dolly
element 3: 5.5
element 4: how are you?


In [20]:
a[0] = 10
a

[10, 'hello', 'Dolly', 5.5, 'how are you?']

In [21]:
a=range(10,19,2)
for i in a:
    print(i)

10
12
14
16
18


In [22]:
try:
    a[0]=33
except:
    print(" 'range' object does not support item assignment ")

 'range' object does not support item assignment 


In [23]:
a=list(a)
a[0]=33
print(a)

[33, 12, 14, 16, 18]


In [24]:
#  Python Tuples:
b = (-1, "bye", 'c')
b

(-1, 'bye', 'c')

In [25]:
b[-1]

'c'

In [26]:
b[0] = 10
b

TypeError: 'tuple' object does not support item assignment

In [ ]:
x, y = b[0:2]

In [ ]:
x

In [ ]:
y

In [ ]:
#  Python Dictionaries (Keys, values)
a = {"name":"Mary", "age":23, "sign":"capricorn"}
a

In [ ]:
a[1]

In [ ]:
a["job"] = "student"
a

In [27]:
department=[a]
b={'name': 'John', 'age': 26, 'sign': 'virgo', 'job': 'tech geek'}
department.append(b)
b={'name': 'Ivy', 'age': 35, 'sign': 'libra', 'job': 'supervisor'}
department.append(b)
department

[[33, 12, 14, 16, 18],
 {'name': 'John', 'age': 26, 'sign': 'virgo', 'job': 'tech geek'},
 {'name': 'Ivy', 'age': 35, 'sign': 'libra', 'job': 'supervisor'}]

In [28]:
company={'name': 'ACME', 'Logistics': department}
print(company['Logistics'][1])
print(company['Logistics'][2]['age'])

{'name': 'John', 'age': 26, 'sign': 'virgo', 'job': 'tech geek'}
35


In [29]:
#  Python Funtions
def f(a, b=4, c=5):
    if a > 2 and b < 10:
        return a
    elif c == 5:
        return b
    else:
        return a + b + c

In [30]:
f(4)

4

In [31]:
f(4, 11)

11

In [32]:
f(4, c=6, b=11)

21

# NumPy: multi-dimensional arrays and scientific computing
https://www.numpy.org/

In [1]:
import numpy as np

In [2]:
a = np.array([0, 2, 4, 6, 8, 10, 12, 14, 16])
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [3]:
a.ndim

1

In [4]:
a.shape

(9,)

In [5]:
a[2]

4

In [6]:
a[2:]

array([ 4,  6,  8, 10, 12, 14, 16])

In [7]:
a[:4]

array([0, 2, 4, 6])

In [8]:
a[2:7]

array([ 4,  6,  8, 10, 12])

In [9]:
a[2:7:2]

array([ 4,  8, 12])

In [10]:
a[-1]

16

In [11]:
a[::-1]

array([16, 14, 12, 10,  8,  6,  4,  2,  0])

In [12]:
a[[0, 4, 5]]

array([ 0,  8, 10])

In [13]:
b = a > 3
b

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [14]:
a[b]

array([ 4,  6,  8, 10, 12, 14, 16])

In [15]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
a.ndim

2

In [17]:
a.shape #  #Lines x #Columns in matrix notation...

(3, 4)

In [18]:
a[1, 2]

6

In [19]:
a[0]

array([0, 1, 2, 3])

In [20]:
a[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [21]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [22]:
a + 10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [23]:
#array([[ 0,  1,  2,  3],
#       [ 4,  5,  6,  7],
#       [ 8,  9, 10, 11]])
a ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [24]:
a * [10, 20, 30, 40]

array([[  0,  20,  60, 120],
       [ 40, 100, 180, 280],
       [ 80, 180, 300, 440]])

In [26]:
[[10], [20], [30]]*a

array([[  0,  10,  20,  30],
       [ 80, 100, 120, 140],
       [240, 270, 300, 330]])

In [27]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [28]:
np.mean(a)

5.5

In [31]:
a.mean(axis=1)

array([1.5, 5.5, 9.5])

In [32]:
np.max(a)

11

In [33]:
np.max(a, axis=1)

array([ 3,  7, 11])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.linspace(2, 27, 11)

array([ 2. ,  4.5,  7. ,  9.5, 12. , 14.5, 17. , 19.5, 22. , 24.5, 27. ])

In [40]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.full((2, 3), 2.5)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [49]:
#NumPy is also very useful to read data files.....
data=np.genfromtxt('files/periodo.csv', delimiter=',', skip_header=1)
print(data.shape)
data

(17, 2)


array([[ 3.4018 ,  0.     ],
       [ 3.40185,  2.     ],
       [ 3.4019 ,  2.     ],
       [ 3.40195,  3.     ],
       [ 3.402  ,  5.     ],
       [ 3.40205,  2.     ],
       [ 3.4021 ,  6.     ],
       [ 3.40215,  8.     ],
       [ 3.4022 , 22.     ],
       [ 3.40225, 34.     ],
       [ 3.4023 , 31.     ],
       [ 3.40235, 10.     ],
       [ 3.4024 ,  4.     ],
       [ 3.40245,  6.     ],
       [ 3.4025 ,  6.     ],
       [ 3.40255,  7.     ],
       [ 3.4026 ,  2.     ]])

# matplotlib: plotting
https://matplotlib.org/

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
#%matplotlib notebook
%matplotlib inline

In [ ]:
x = np.linspace(-5, 5, 50)
y = np.sin(x)
y2 = y ** 2
y3 = -x / 5

In [ ]:
plt.figure()
plt.plot(x, y, label='sin')
plt.plot(x, y2, '.', label='$\sin^{2}$')
plt.plot(x, y3, linewidth=3)
plt.annotate('example text', xy=(0.5, -0.75))
plt.xlabel("X axis")
plt.ylabel("Y axis")
plt.title("Example plot")
plt.legend()
plt.show()

In [ ]:
fig, ax = plt.subplots(2, sharex=True)
ax[0].plot(x, y)
ax[1].plot(x, y2)
ax[1].set_ylabel('y axis')
plt.show()

In [ ]:
y, x = np.mgrid[0:20, 0:30]
z = (x - 4)**2+ y**2
plt.figure()
plt.pcolormesh(x, y, z, shading='auto')
plt.show()

# SciPy: extra modules for scientific computation
https://www.scipy.org/

In [ ]:
from scipy.optimize import curve_fit
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
def f(x, a, b, c):
    return a * np.exp(-b * x) + c

In [ ]:
n = 60
x = np.linspace(0, 5, n)
y = f(x, 5, 2, 0.5) + 2 * np.random.rand(n)

In [ ]:
popt, pcov = curve_fit(f, x, y)
perr = np.sqrt(np.diag(pcov))
y_fit = f(x, *popt)
msd = np.sum((y - y_fit) ** 2) / n

In [ ]:
pnames = ['a', 'b', 'c']
results = ''
for name, value, error in zip(pnames, popt, perr):
    results += '{} = {:.2f}$\pm${:.2f}\n'.format(name, value, error)
results += 'MSD = {:.2f}'.format(msd)
    
plt.plot(x, y, '.', label='data')
plt.plot(x, y_fit, label='fit: $ae^{-bx} + c$')
plt.annotate(results, xy=(0.7, 0.55), xycoords='axes fraction')
plt.legend()
plt.show()

In [ ]:
%run langmuir_fit.py
